apiVersion: v1
kind: ConfigMap

metadata:
  name: app-config

data: development_debug_status:true
  staging_debug_status:false
  production_debug_status:false

  development_log_level:debug
  staging_log_level:info
  production_log_level:warning

  development_max_connections:10
  staging_max_connections:50
  production_max_connections:100
